version: '3'
services:
  app1:
    image: app1-image
    container_name: container-app1
    ports:
      - "4000:4000"

  app2:
    image: app2-image
    container_name: container-app2
    ports:
      - "4001:4001"
    depends_on:
      - app1
